dir /b .\*.rpm > rpm更新.txt
dir /b V:\Packages\*.rpm | findstr ^^audit-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^apr-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^apr-util-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^audit-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^audit-libs-python-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^autogen-libopts-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^bzip2-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^checkpolicy-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^copy-jdk-configs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^cryptsetup-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^cryptsetup-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^cryptsetup-python-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^dejavu-fonts-common-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^dejavu-sans-fonts-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^dejavu-sans-mono-fonts-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^dejavu-serif-fonts-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^dwz-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^e2fsprogs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^e2fsprogs-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^elfutils-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^elfutils-default-yama-scope-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^elfutils-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^elfutils-libelf-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^elfutils-libelf-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^elfutils-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^fontconfig-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^fontpackages-filesystem-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^fping-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^freetype-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^gdb-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^gdbm-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^giflib-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^glibc-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^glibc-common-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^glibc-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^glibc-headers-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^gnutls-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^gnutls-dane-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^gnutls-utils-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^grafana-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^httpd-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^httpd-tools-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^iksemel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^java-1.8.0-openjdk-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^java-1.8.0-openjdk-headless-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^javapackages-tools-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^json-c-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^kernel-headers-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^keyutils-libs-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^krb5-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^krb5-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^krb5-pkinit-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^krb5-server-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^krb5-workstation-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libcgroup-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libcgroup-tools-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libcom_err-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libcom_err-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libdb-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libdb-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libdb-utils-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libevent-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libfontenc-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libgudev1-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libICE-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libjpeg-turbo-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libkadm5-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libpng-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libselinux-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libselinux-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libselinux-python-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libselinux-utils-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libsemanage-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libsemanage-python-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libsepol-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libsepol-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libSM-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libss-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libtasn1-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libtool-ltdl-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libverto-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libverto-libevent-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libX11-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libX11-common-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libX11-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libXau-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libXau-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libxcb-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libxcb-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libXcomposite-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libXext-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libXi-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libXpm-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libXrender-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libxslt-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libXtst-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^libzip-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^lksctp-tools-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^lm_sensors-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^lm_sensors-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^lz4-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^mailcap-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^mariadb-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^mariadb-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^mariadb-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^mariadb-server-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^mod_session-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^net-snmp-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^net-snmp-agent-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^net-snmp-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^net-snmp-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^net-snmp-utils-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^nettle-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^net-tools-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^nspr-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^nss-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^nss-softokn-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^nss-softokn-freebl-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^nss-sysinit-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^nss-tools-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^nss-util-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^OpenIPMI-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^OpenIPMI-modalias-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^openssl-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^openssl-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^openssl-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^p11-kit-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^p11-kit-trust-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^patch-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^pcre-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^pcre-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Algorithm-Diff-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Archive-Extract-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Archive-Zip-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Business-ISBN-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Business-ISBN-Data-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Carp-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Compress-Raw-Bzip2-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Compress-Raw-Zlib-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-constant-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-CPAN-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-CPAN-Meta-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-CPAN-Meta-Requirements-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-CPAN-Meta-YAML-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-CPANPLUS-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Data-Dumper-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-DBD-MySQL-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-DBD-SQLite-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-DBI-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-DBIx-Simple-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Digest-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Digest-MD5-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Digest-SHA1-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Digest-SHA-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Encode-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Encode-Locale-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Exporter-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-ExtUtils-CBuilder-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-ExtUtils-Install-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-ExtUtils-MakeMaker-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-ExtUtils-Manifest-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-ExtUtils-ParseXS-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-File-Fetch-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-File-Listing-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-File-Path-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-File-Remove-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-File-Temp-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Filter-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Getopt-Long-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-HTML-Parser-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-HTML-Tagset-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-HTTP-Cookies-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-HTTP-Daemon-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-HTTP-Date-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-HTTP-Message-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-HTTP-Negotiate-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-HTTP-Tiny-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-IO-Compress-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-IO-HTML-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-IO-Socket-IP-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-IO-Socket-SSL-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-IPC-Cmd-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-JSON-PP-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-libwww-perl-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Locale-Maketext-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Locale-Maketext-Simple-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-local-lib-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Log-Message-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Log-Message-Simple-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-LWP-MediaTypes-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-macros-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-Build-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-CoreList-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-Install-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-Load-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-Load-Conditional-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-Loaded-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-Metadata-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-Pluggable-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-ScanDeps-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Module-Signature-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Mozilla-CA-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Net-Daemon-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Net-HTTP-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Net-LibIDN-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Net-SSLeay-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Object-Accessor-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Package-Constants-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Params-Check-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-PAR-Dist-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-parent-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Parse-CPAN-Meta-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-PathTools-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Perl-OSType-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-PlRPC-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Pod-Escapes-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-podlators-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Pod-Perldoc-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Pod-Simple-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Pod-Usage-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Scalar-List-Utils-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Socket-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-srpm-macros-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Storable-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Term-UI-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Test-Harness-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Text-Diff-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Text-ParseWords-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Thread-Queue-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-threads-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-threads-shared-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-TimeDate-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Time-HiRes-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-Time-Local-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-URI-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-version-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-WWW-RobotRules-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^perl-YAML-Tiny-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-bcmath-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-cli-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-common-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-fpm-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-gd-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-ldap-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-mbstring-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-mysql-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-odbc-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-pdo-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-pear-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-process-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-snmp-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-xml-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^php-xmlrpc-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^pkgconfig-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^policycoreutils-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^policycoreutils-python-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^popt-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^pyparsing-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^python-IPy-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^python-javapackages-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^python-lxml-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^redhat-rpm-config-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^rpm-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^rpm-build-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^rpm-build-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^rpm-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^rpm-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^rpm-python-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^rpm-sign-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^selinux-policy-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^selinux-policy-targeted-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^setools-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^systemd-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^systemd-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^systemd-python-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^systemd-sysv-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^systemtap-sdt-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^t1lib-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^tcp_wrappers-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^trousers-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^ttmkfdir-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^tzdata-java-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^unbound-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^unixODBC-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^unzip-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^urw-fonts-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^words-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^xorg-x11-fonts-Type1-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^xorg-x11-font-utils-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^xorg-x11-proto-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^xz-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^xz-devel-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^xz-libs-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zabbix-agent-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zabbix-java-gateway-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zabbix-proxy-mysql-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zabbix-release-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zabbix-server-mysql-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zabbix-web-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zabbix-web-mysql-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zip-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zlib-[0-9] | findstr /i /r /v i686>> $$
dir /b V:\Packages\*.rpm | findstr ^^zlib-devel-[0-9] | findstr /i /r /v i686>> $$
for /f "delims=" %%a in ($$) do (
	copy "V:\Packages\%%~a" ..\
	echo %%~a >> rpm更新.log
)
copy ".\fping-*" ..\>> rpm更新.log
copy ".\iksemel-*" ..\>> rpm更新.log
copy .\zabbix-* ..\>> rpm更新.log
del rpm更新.log
del rpm更新.txt
del $$
pause